### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by uname** [sharpdeep/WxRobot#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\DevTool\Python27\lib\site-packages\wxrobot-0.13-py2.7.egg\WxRobot\webwxapi.py", line 626
    def textFilter(self,*args,beside = False):
                                   ^
SyntaxError: invalid syntax

**Comment by sharpdeep** [comment]
我是用py3写的，没有在py2测试过

**Comment by Arvin2015** [comment]
把文件保存一下，不要直接粘贴进去就运行，你试试可不可以，我在py2上是可以用的

**Comment by szad670401** [comment]
我也遇到同样的问题

**Comment by Bnij** [comment]
我也遇到了这个问题 我想问一下怎么解决

**Comment by wuzhengyi** [comment]
同问
